AWSTemplateFormatVersion: '2010-09-09'
Description: Create a VPC peering connection between shared-system and dev-system networks.

Resources:
  VpcPeeringConnection:
    Type: 'AWS::EC2::VPCPeeringConnection'
    Properties:
      VpcId: !ImportValue shared-system-VpcId
      PeerVpcId: !ImportValue dev-system-VpcId
      Tags:
        - Key: Name
          Value: VPC Peering between shared-system and dev-system
